Add authentication on client.
trakx/trakx-tools pull request #302
Opened 2020-12-08 22:32 UTC by AymericNoel

I have implemented a functionnal way to log-in in client with google, to restrict some pages to non connected user.

I have found the way to send tokens to server, it  should be implemented by the end of the week !

2020-12-10 13:53 UTC, AymericNoel commented on src/Trakx.IndiceManager.Client/Pages/IndexComposition/IndexList.razor
> +        catch (Exception e)
```suggestion
        catch
```

2020-12-10 18:12 UTC, monsieurleberre requested changes
Please try to factor authentication and make it easilly interchangeable (as discussed on slack)

2020-12-10 18:12 UTC, monsieurleberre commented on src/Trakx.IndiceManager.Client/Pages/IndexMarketplace/IndexBalances.razor
> +        await DataGrid.CsvExport();
👍

2020-12-10 18:12 UTC, monsieurleberre commented on src/Trakx.IndiceManager.Client/Pages/IndexComposition/IndexList.razor
> +        {
strange this thing about the toaster...

2020-12-10 18:12 UTC, monsieurleberre commented on src/Trakx.IndiceManager.ApiClient/ServiceConfiguration.cs
> +            serviceCollection.AddSingleton<IIndiceCreationClient, IndiceCreationClient>(serviceProvider => new IndiceCreationClient(baseUrl, new HttpClient(clientHandler), serviceProvider.GetService<
Here there should be a common interface to share for authentication (or we can think that we could also have an array of implementations that can get injected, but definitely an overkill for now), both via Google or via Envoy

2020-12-10 18:12 UTC, monsieurleberre commented on src/Trakx.IndiceManager.ApiClient/AuthorisedClient.cs
> +            #region envoy authentication
I agree with codacy here, there is too much commented code. It is never simple to do, but Envoy authentication or google authentication are just authentications, and they shouldn't affect the code in too many places, so the comments should naturally go away.

2020-12-10 18:15 UTC, AymericNoel commented on src/Trakx.IndiceManager.Client/Pages/IndexComposition/IndexList.razor
> +        {
Yes ! try to remove the autorize attribute at the top of the razor page, then request that page without be connected, as the controller has the authorize attiribute, an error will be thrown and then an exception will stop the client...

2020-12-11 14:39 UTC, AymericNoel commented on src/Trakx.IndiceManager.Client/Pages/IndexComposition/IndexList.razor
> +        {
Maybe we should initialize components with error toaster in other block than `OnInitializedAsync `...

2020-12-12 09:09 UTC, monsieurleberre commented on src/Trakx.IndiceManager.Client/Pages/IndexComposition/IndexList.razor
> +        {
yes that is my feeling too 🤔

2020-12-12 19:56 UTC, monsieurleberre reviewed
I wil try to make it even better tomorrow but that is already a great refactoring 💪👍

2020-12-14 11:19 UTC, monsieurleberre reviewed
There is still a bit of testing to be done here

2020-12-14 16:04 UTC, merged