Readme env
trakx/trakx-tools pull request #367
Opened 2021-01-06 01:50 UTC by carlos-takeapps

final version
synched with dev

2021-01-06 07:20 UTC, monsieurleberre requested changes
I am not sure I understand everything as per my comments, however, you can't start duplicating classes.

2021-01-06 07:20 UTC, monsieurleberre commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                var instance = Activator.CreateInstance(x, new object[] { });
Can you explain why you actually create all these objects?

2021-01-06 07:20 UTC, monsieurleberre commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                    var attribute = property.GetCustomAttribute(typeof(ReadmeDocumentAttribute)) as ReadmeDocumentAttribute;
I usually prefer this more recent syntax
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#type-testing-with-pattern-matching
no big deal :)

2021-01-06 07:20 UTC, monsieurleberre commented on src/Trakx.Common/Configuration/EnvironmentConfiguration.cs
> +    public class EnvironmentConfiguration
Shouldn't this come as a result of fiding a reference to the `Trakx.CryptoCompare.ApiClient` package?
If now have to maintain this file manually I think we lost the whole point of this enhancement?
Sorry, maybe there is something I don't understand about this file...

Also please check if you can remove all the warnings below if this file is needed, thanks

2021-01-06 07:20 UTC, monsieurleberre commented on src/Trakx.Common/Configuration/ReadmeDocumentAttribute.cs
> +    public class ReadmeDocumentAttribute : Attribute
No!! You wrote this class
https://github.com/trakx/dotnet-utils/blob/dev/src/Trakx.Utils/Attributes/ReadmeDocumentAttribute.cs
and should re-use it, not duplicate it...

2021-01-06 15:23 UTC, carlos-takeapps commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                var instance = Activator.CreateInstance(x, new object[] { });
Because I passed a value to the attribute so we can have cleaner property names mapped to the env var name

```
        [ReadmeDocument("CryptoCompareApiConfiguration__ApiKey")]
        public string CryptoCompareApiKey { get; set; }
```

So I need to get an instance of the class to get the var name that the property is related to.

I was trying to avoid something like 

```
        public string CryptoCompareApiConfiguration__ApiKey{ get; set; }
```

But I can revert that to this last option, which may be simplier to handle.

2021-01-06 15:31 UTC, carlos-takeapps commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                    var attribute = property.GetCustomAttribute(typeof(ReadmeDocumentAttribute)) as ReadmeDocumentAttribute;
OK, yes. I wanted more control about the GetCustomAttribute() returning no values, but I will change and test it.

2021-01-06 15:34 UTC, carlos-takeapps commented on src/Trakx.Common/Configuration/ReadmeDocumentAttribute.cs
> +    public class ReadmeDocumentAttribute : Attribute
Yes, but I was waiting that package to get published, so in the meanwhile I worked to the local class. I wanted to make sure this approach was approved and have already a new branch for deleting this file and taking the class from the package. I will make that change in this same branch.

2021-01-06 15:42 UTC, carlos-takeapps commented on src/Trakx.Common/Configuration/EnvironmentConfiguration.cs
> +    public class EnvironmentConfiguration
I thing initially didn't know -or I missed- about this configuration class, that's why I created a local class to be able to work with.  I think it is also the situation as the following comment, if we get this approach approved, I can go and make the changes in other packages and remove these local files. But I wasn't sure about having so many PRs ongoing on many different branches and get things lost.
For example, I would like to first confirm if it is OK for you to pass the var name to the ReadmeDocumentAttribute (see the first conversation) and then, get into another packages and projects to apply the needed changes. Otherwise every correction on this PR would span updates on all the PRs on different branches being worked. I apologize if I was not clear and tell me, please, if you rather use a different approach.

2021-01-06 16:01 UTC, carlos-takeapps commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                    var attribute = property.GetCustomAttribute(typeof(ReadmeDocumentAttribute)) as ReadmeDocumentAttribute;
changed

2021-01-06 23:50 UTC, monsieurleberre commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                var instance = Activator.CreateInstance(x, new object[] { });
no no, my question is not about adding the name from the attribute, I actually like that 👍. I am wondering why we need to call `Activator.CreateInstance(x, new object[] { })` which seems potentially very expensive.

2021-01-06 23:50 UTC, monsieurleberre commented on src/Trakx.Common/Configuration/EnvironmentConfiguration.cs
> +    public class EnvironmentConfiguration
Yes yes for sure, but I saw and approved that PR on dotnet-utils : https://github.com/trakx/dotnet-utils/pull/16
To me it means I am happy with the approach.
When I disagree, I try to explain why, and try to resist the merge, like I am doing now 😉😅

2021-01-07 12:41 UTC, carlos-takeapps commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                var instance = Activator.CreateInstance(x, new object[] { });
Since the name is paased as a parameter to the attribute, the only way I've found to retrieve the name is by instantiating the class (which forces the call to the attribute constructor) and then retrieve the var name from the object instance attribute. Let me see again if I can use reflection on the type and get the var name without instantiating the object.

2021-01-07 12:44 UTC, carlos-takeapps commented on src/Trakx.Common/Configuration/EnvironmentConfiguration.cs
> +    public class EnvironmentConfiguration
OK. I think that first I need to solve the issue with the object instantiation and the var name, once I get that solved, I can adjust the Attribute in the other package, merge and publish, and then reference it from this project and delete the local classes.

2021-01-07 21:09 UTC, carlos-takeapps commented on src/Trakx.Common/Configuration/EnvironmentConfiguration.cs
> +    public class EnvironmentConfiguration
Removed

2021-01-07 21:10 UTC, carlos-takeapps commented on src/Trakx.Common/Configuration/ReadmeDocumentAttribute.cs
> +    public class ReadmeDocumentAttribute : Attribute
Removed

2021-01-07 21:10 UTC, carlos-takeapps commented on src/Trakx.Common.Tests/Unit/Config/ConfigurationProviderTests.cs
> +                                var instance = Activator.CreateInstance(x, new object[] { });
Removed the instantiation

2021-01-07 21:39 UTC, carlos-takeapps commented
I thought adding to `Trakx.Common.Tests ` a reference to `Trakx.CriptoCompare.ApiClient` so the `CryptoCompareApiConfiguration ` class is documented on this project's Environment.md . 
The thing is that it would create a circular reference between nuget packages. 
I need to dig a little bit more in detail and I am not sure if we want all the different packages to be referenced by this project in order to document all environment variables. 
Maybe it is better to have here a class with a unit test that may be imported from this package by all other projects so the test runs and create a specific Environment.md for each package.

Let me know your thoughts please.

2021-01-08 07:06 UTC, monsieurleberre commented
> I thought adding to `Trakx.Common.Tests ` a reference to `Trakx.CriptoCompare.ApiClient` so the `CryptoCompareApiConfiguration ` class is documented on this project's Environment.md .
> The thing is that it would create a circular reference between nuget packages.
> I need to dig a little bit more in detail and I am not sure if we want all the different packages to be referenced by this project in order to document all environment variables used across all our libraries and packages.
> Maybe it is better to have here a class with a unit test exported from this project, that may be imported from this package by all other projects so the test runs and create a specific Environment.md for each package.
> 
> Let me know your thoughts please.

I feel that this is the reason you created the Trakx.Utils.Testing package.

2021-01-19 12:40 UTC, monsieurleberre commented
done separately

2021-01-19 12:40 UTC, closed without merging